# Generated by Django 2.1 on 2020-08-04 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 17, 55, 51, 267751, tzinfo=utc)),
        ),
    ]
